<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config.php';

function e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function csrf(): string { return $_SESSION['csrf'] ??= bin2hex(random_bytes(32)); }
function productImage(string $path): string {
    $path = trim($path);
    if ($path !== '' && is_file(__DIR__ . '/' . $path)) return $path;
    $fallback = basename(pathinfo($path, PATHINFO_FILENAME)) . '.webp';
    return $fallback !== '.webp' && is_file(__DIR__ . '/imagens/' . $fallback) ? 'imagens/' . $fallback : '';
}

$user = $_SESSION['user'] ?? null;
if (!$user) { header('Location: index.php'); exit; }
if (!empty($user['is_admin'])) { header('Location: index.php'); exit; }
$flash = $_SESSION['flash'] ?? null; unset($_SESSION['flash']);
$pdo = db();
$products = $pdo->query('SELECT p.*, (SELECT COUNT(*) FROM comentarios c WHERE c.produto_id=p.id) total_comentarios FROM produtos p WHERE p.status=1 ORDER BY p.nome')->fetchAll();
$stats = $pdo->query('SELECT COUNT(*) total, COALESCE(SUM(quantidade),0) unidades, COALESCE(SUM(quantidade<=5),0) baixo FROM produtos WHERE status=1')->fetch();
$comments = []; $history = [];
foreach ($products as $product) {
    $stmt = $pdo->prepare('SELECT c.texto,c.data_comentario,u.nome FROM comentarios c JOIN usuarios u ON u.id=c.usuario_id WHERE c.produto_id=? ORDER BY c.data_comentario DESC,c.id DESC');
    $stmt->execute([$product['id']]); $comments[$product['id']] = $stmt->fetchAll();
    $stmt = $pdo->prepare('SELECT m.tipo,m.quantidade,m.data_movimentacao,m.observacoes,u.nome usuario FROM movimentacoes m JOIN usuarios u ON u.id=m.usuario_id WHERE m.produto_id=? ORDER BY m.data_movimentacao DESC,m.id DESC');
    $stmt->execute([$product['id']]); $history[$product['id']] = $stmt->fetchAll();
}
$initials = implode('', array_map(fn($part) => mb_substr($part, 0, 1), array_slice(preg_split('/\s+/', trim($user['nome'])), 0, 2)));
?><!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#F2E9D8"><title>Consultar estoque · StockControl</title><link rel="stylesheet" href="assets/style.css"></head>
<body class="employee-view"><div class="app-shell">
<aside class="sidebar"><a class="brand" href="estoque.php"><img src="assets/stockcontrol.svg" alt="StockControl"></a><nav class="side-nav"><a class="selected" href="#produtos" title="Consultar estoque" aria-label="Consultar estoque"><span>▤</span>Estoque</a><a href="#produtos" title="Produtos" aria-label="Produtos"><span>▦</span>Produtos</a></nav><div class="sidebar-bottom"><div class="profile"><span class="avatar"><?=e($initials)?></span><span class="profile-copy"><b><?=e($user['nome'])?></b><small>Funcionário</small></span></div><form method="post" action="index.php"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><button class="logout" name="action" value="logout" title="Sair" aria-label="Sair">↪ <span>Sair da conta</span></button></form></div></aside>
<main class="main-content" id="painel"><div class="insight-banner"><span class="banner-mark">✳</span><span>Consulta do estoque · dados atualizados nesta página</span><strong><?= (int)$stats['baixo'] ?> itens com estoque baixo</strong></div>
<header class="page-head"><div><div class="eyebrow">STOCKCONTROL · ÁREA DO FUNCIONÁRIO</div><h1>Olá, <?=e(explode(' ',trim($user['nome']))[0])?></h1><p class="muted">Consulte produtos, preços e quantidades disponíveis.</p></div><span class="staff-role">Funcionário</span></header>
<?php if($flash): ?><div class="notice <?=e($flash[1])?>"><?=e($flash[0])?></div><?php endif; ?>
<section class="stats-grid staff-stats"><article class="stat-card"><div class="stat-heading">Produtos ativos <span class="stat-icon">▤</span></div><strong><?=number_format((int)$stats['total'],0,',','.')?></strong><small>Produtos disponíveis para consulta</small></article><article class="stat-card"><div class="stat-heading">Unidades em estoque <span class="stat-icon">▣</span></div><strong><?=number_format((int)$stats['unidades'],0,',','.')?></strong><small>Quantidade total disponível</small></article><article class="stat-card"><div class="stat-heading">Estoque baixo <span class="stat-icon">⌁</span></div><strong><?=number_format((int)$stats['baixo'],0,',','.')?></strong><small class="wine-text">5 unidades ou menos</small></article></section>
<section class="products-section employee-products" id="produtos"><div class="section-heading"><div><span class="eyebrow">CATÁLOGO</span><h2>Estoque disponível</h2><p class="muted">Veja a quantidade e o preço de cada produto ativo.</p></div><span class="item-count"><?=count($products)?> produtos</span></div><div class="search-wrap"><span>⌕</span><input id="productSearch" type="search" placeholder="Buscar produto..." oninput="filterProducts()"></div><div class="product-list" id="productList">
<?php foreach($products as $product): $low=(int)$product['quantidade']<=5; $photo=productImage((string)$product['imagem']); ?><article class="product-card" data-search="<?=e(mb_strtolower($product['nome'].' '.$product['descricao']))?>"><div class="product-image"><?php if($photo!==''): ?><img src="<?=e($photo)?>" alt="<?=e($product['nome'])?>"><?php else: ?><span>□</span><?php endif; ?><span class="photo-tag"><?=$low?'Estoque baixo':'Em estoque'?></span><div class="product-actions"><button class="text-button" onclick="showComments(<?= (int)$product['id'] ?>,<?=e(json_encode($product['nome'],JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_TAG|JSON_HEX_AMP))?>)" title="Comentários" aria-label="Ver comentários">☷</button><button class="text-button" onclick="showHistory(<?= (int)$product['id'] ?>,<?=e(json_encode($product['nome'],JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_TAG|JSON_HEX_AMP))?>)" title="Histórico" aria-label="Ver histórico">↶</button></div></div><div class="product-main"><div class="product-title-row"><h3><?=e($product['nome'])?></h3></div><div class="product-meta"><span>R$ <?=number_format((float)$product['preco'],2,',','.')?></span><b><?=number_format((int)$product['quantidade'],0,',','.')?> un.</b></div></div></article><?php endforeach; ?>
<?php if(!$products): ?><div class="empty-state">Nenhum produto ativo cadastrado ainda.</div><?php endif; ?><div id="noResults" class="empty-state hidden">Nenhum produto corresponde à busca.</div></div></section>
</main></div>
<dialog id="commentsDialog" class="dialog"><div class="dialog-head"><div><h2 id="commentsTitle">Comentários</h2><p>Observações mais recentes primeiro.</p></div><button type="button" class="close-button" onclick="closeDialog('commentsDialog')">×</button></div><div id="commentsList" class="comments-list"></div><form method="post" action="index.php" class="comment-form"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="comment"><input type="hidden" name="produto_id" id="commentProductId"><label class="field">Adicionar comentário<textarea name="texto" required placeholder="Escreva uma observação..."></textarea></label><div class="dialog-actions"><button type="button" class="button secondary" onclick="closeDialog('commentsDialog')">Fechar</button><button class="button primary">Cadastrar</button></div></form></dialog>
<dialog id="historyDialog" class="dialog"><div class="dialog-head"><div><h2 id="historyTitle">Histórico</h2><p>Entradas e saídas registradas para o produto.</p></div><button type="button" class="close-button" onclick="closeDialog('historyDialog')">×</button></div><div id="historyList" class="comments-list"></div><div class="dialog-actions"><button type="button" class="button secondary" onclick="closeDialog('historyDialog')">Fechar</button></div></dialog>
<script>const commentData=<?=json_encode($comments,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP)?>;const historyData=<?=json_encode($history,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP)?>;function openDialog(id){document.getElementById(id).showModal()}function closeDialog(id){document.getElementById(id).close()}function safeText(text){let node=document.createElement('p');node.textContent=text;return node.innerHTML}function filterProducts(){let query=document.getElementById('productSearch').value.toLocaleLowerCase('pt-BR'),shown=0;document.querySelectorAll('.product-card').forEach(card=>{let match=card.dataset.search.includes(query);card.classList.toggle('hidden',!match);if(match)shown++});document.getElementById('noResults').classList.toggle('hidden',shown!==0)}function showComments(id,name){document.getElementById('commentsTitle').textContent='Comentários · '+name;document.getElementById('commentProductId').value=id;let data=commentData[id]||[];document.getElementById('commentsList').innerHTML=data.length?data.map(c=>'<article class="comment-item"><b>'+safeText(c.nome)+'</b><time>'+new Date(c.data_comentario.replace(' ','T')+'Z').toLocaleString('pt-BR')+'</time><p>'+safeText(c.texto)+'</p></article>').join(''):'<p class="empty-state">Ainda não há comentários para este produto.</p>';openDialog('commentsDialog')}function showHistory(id,name){document.getElementById('historyTitle').textContent='Histórico · '+name;let data=historyData[id]||[];document.getElementById('historyList').innerHTML=data.length?data.map(m=>'<article class="comment-item"><b>'+safeText(m.tipo==='entrada'?'Entrada':'Saída')+' · '+Number(m.quantidade)+' unidade(s)</b><time>'+new Date(m.data_movimentacao.replace(' ','T')+'Z').toLocaleString('pt-BR')+'</time><p>Responsável: '+safeText(m.usuario)+(m.observacoes?'<br>'+safeText(m.observacoes):'')+'</p></article>').join(''):'<p class="empty-state">Nenhuma movimentação registrada para este produto.</p>';openDialog('historyDialog')}</script></body></html>
