<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config.php';

function e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
$user = $_SESSION['user'] ?? null;
if (!$user) { header('Location: index.php'); exit; }
$pdo = db();
$movements = $pdo->query('SELECT m.id,m.tipo,m.quantidade,m.data_movimentacao,m.observacoes,p.nome produto,u.nome usuario FROM movimentacoes m JOIN produtos p ON p.id=m.produto_id JOIN usuarios u ON u.id=m.usuario_id ORDER BY m.data_movimentacao DESC,m.id DESC')->fetchAll();
$summary = $pdo->query("SELECT COUNT(*) total, COALESCE(SUM(tipo='entrada'),0) entradas, COALESCE(SUM(tipo='saida'),0) saidas FROM movimentacoes")->fetch();
$initials = implode('', array_map(fn($part) => mb_substr($part, 0, 1), array_slice(preg_split('/\s+/', trim($user['nome'])), 0, 2)));
$home = !empty($user['is_admin']) ? 'index.php' : 'estoque.php';
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#F2E9D8"><title>Movimentações · StockControl</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="app-shell">
<aside class="sidebar"><a class="brand" href="<?=e($home)?>"><img src="assets/stockcontrol.svg" alt="StockControl"></a><nav class="side-nav"><a href="<?=e($home)?>" title="Painel" aria-label="Painel"><span>▦</span>Painel</a><?php if(!empty($user['is_admin'])): ?><a href="index.php#produtos" title="Produtos" aria-label="Produtos"><span>▤</span>Produtos</a><?php else: ?><a href="estoque.php#produtos" title="Estoque" aria-label="Estoque"><span>▤</span>Estoque</a><?php endif; ?><a class="selected" href="movimentacoes.php" title="Movimentações" aria-label="Movimentações"><span>↕</span>Movimentações</a></nav><div class="sidebar-bottom"><div class="profile"><span class="avatar"><?=e($initials)?></span><span class="profile-copy"><b><?=e($user['nome'])?></b><small><?=!empty($user['is_admin'])?'Administrador':'Funcionário'?></small></span></div><form method="post" action="index.php"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'] ?? '')?>"><button class="logout" name="action" value="logout" title="Sair" aria-label="Sair">↪ <span>Sair da conta</span></button></form></div></aside>
<main class="main-content"><div class="insight-banner"><span class="banner-mark">↕</span><span>Registro de entradas e saídas do estoque</span><strong><?=number_format((int)$summary['total'],0,',','.')?> movimentações</strong></div><header class="page-head"><div><div class="eyebrow">STOCKCONTROL · HISTÓRICO</div><h1>Movimentações</h1><p class="muted">Consulte quando o estoque mudou, por quem e em qual quantidade.</p></div><a class="button primary" href="<?=e($home)?>#produtos">Voltar aos produtos</a></header>
<section class="stats-grid movement-stats"><article class="stat-card"><div class="stat-heading">Total de registros <span class="stat-icon">↕</span></div><strong><?=number_format((int)$summary['total'],0,',','.')?></strong><small>Histórico completo</small></article><article class="stat-card"><div class="stat-heading">Entradas <span class="stat-icon">↙</span></div><strong><?=number_format((int)$summary['entradas'],0,',','.')?></strong><small>Reposições e recebimentos</small></article><article class="stat-card"><div class="stat-heading">Saídas <span class="stat-icon">↗</span></div><strong><?=number_format((int)$summary['saidas'],0,',','.')?></strong><small>Retiradas do estoque</small></article></section>
<section class="products-section movement-history"><div class="section-heading"><div><span class="eyebrow">HISTÓRICO COMPLETO</span><h2>Entradas e saídas</h2><p class="muted">Cada registro mostra produto, quantidade, responsável, data e observação.</p></div></div><div class="movement-filters"><label class="search-wrap"><span>⌕</span><input id="movementSearch" type="search" placeholder="Buscar produto ou responsável..." oninput="filterMovements()"></label><select id="movementType" class="filter" onchange="filterMovements()"><option value="">Todos os tipos</option><option value="entrada">Entradas</option><option value="saida">Saídas</option></select></div>
<div class="movement-table-wrap"><table class="movement-table"><thead><tr><th>Tipo</th><th>Produto</th><th>Quantidade</th><th>Responsável</th><th>Data</th><th>Observação</th></tr></thead><tbody id="movementRows"><?php foreach($movements as $m): ?><tr data-type="<?=e($m['tipo'])?>" data-search="<?=e(mb_strtolower($m['produto'].' '.$m['usuario'].' '.($m['observacoes'] ?? '')))?>"><td><span class="movement-type <?=e($m['tipo'])?>"><?=$m['tipo']==='entrada'?'↙ Entrada':'↗ Saída'?></span></td><td><b><?=e($m['produto'])?></b></td><td class="movement-quantity <?=$m['tipo']==='saida'?'negative':''?>"><?=$m['tipo']==='entrada'?'+':'−'?><?=number_format((int)$m['quantidade'],0,',','.')?> un.</td><td><?=e($m['usuario'])?></td><td><?=e((new DateTime($m['data_movimentacao']))->format('d/m/Y · H:i'))?></td><td><?=e($m['observacoes'] ?: '—')?></td></tr><?php endforeach; ?><?php if(!$movements): ?><tr><td colspan="6" class="empty-state">Ainda não há movimentações registradas.</td></tr><?php endif; ?></tbody></table><div id="movementEmpty" class="empty-state hidden">Nenhuma movimentação corresponde aos filtros.</div></div></section>
</main></div><script>function filterMovements(){let q=document.getElementById('movementSearch').value.toLocaleLowerCase('pt-BR'),type=document.getElementById('movementType').value,shown=0;document.querySelectorAll('#movementRows tr[data-type]').forEach(row=>{let visible=(!type||row.dataset.type===type)&&row.dataset.search.includes(q);row.classList.toggle('hidden',!visible);if(visible)shown++});document.getElementById('movementEmpty').classList.toggle('hidden',shown!==0)}</script></body></html>
